import type { FormSection } from "@/types/form"

// Verified and rewritten formSections configuration
export const formSections: FormSection[] = [
  {
    title: "INFORMAÇÕES BÁSICAS DA EMPRESA",
    description: "Vamos começar conhecendo um pouco sobre sua empresa",
    steps: [
      {
        id: "company_name",
        type: "input",
        question: "Qual o nome da sua empresa?",
        placeholder: "Digite o nome da sua empresa",
        example: "Brazilian Brain, Tech Solutions, etc.",
        required: true,
      },
      {
        id: "company_sector",
        type: "textarea",
        question: "Qual o setor da sua empresa?",
        placeholder: "Descreva o setor de atuação",
        example: "Somos uma empresa de software B2B que oferece soluções de gestão empresarial",
        required: true,
      },
      {
        id: "company_website",
        type: "input",
        question: "Sua empresa tem site?",
        placeholder: "www.exemplo.com.br",
        example: "www.techsolutions.com.br - Importante para que o Agente possa direcionar leads para mais informações",
        required: false,
      },
      {
        id: "company_description",
        type: "textarea",
        question: "Conte um pouco sobre sua empresa: o que vocês fazem?",
        placeholder: "Descreva as principais atividades da sua empresa",
        example: "Desenvolvemos software de gestão empresarial que ajuda empresas a automatizar processos internos",
        required: true,
      },
      {
        id: "company_products",
        type: "textarea",
        question: "Quais são os principais produtos/serviços da sua empresa?",
        placeholder: "Liste seus principais produtos/serviços",
        example: "Sistema ERP, Módulo Financeiro, Módulo RH, Módulo Vendas",
        required: true,
      },
      {
        id: "ideal_customer",
        type: "textarea",
        question: "Qual é o perfil ideal do seu cliente (ICP)?",
        placeholder: "Descreva seu cliente ideal",
        example: "Empresas de médio porte, com faturamento acima de 5M/ano, que precisam automatizar processos",
        required: true,
      },
    ],
  },
  {
    title: "IDENTIDADE DO AGENTE",
    description: "Configure a personalidade e comportamento do seu Agente SDR",
    steps: [
      {
        id: "agent_name",
        type: "input",
        question: "Qual será o nome do seu Agente SDR?",
        placeholder: "Digite o nome do Agente",
        example: "Ana Silva, representante comercial da Tech Solutions",
        required: true,
      },
      {
        id: "agent_presentation",
        type: "textarea",
        question: "Como você quer que seu Agente SDR se apresente?",
        placeholder: "Digite a mensagem de apresentação",
        example:
          "Olá! Sou Ana da Tech Solutions, especialista em soluções de gestão empresarial. Vi que você tem interesse em melhorar seus processos internos.",
        required: true,
      },
      {
        id: "agent_personality",
        type: "textarea",
        question: "Qual será a personalidade do seu Agente SDR?",
        placeholder: "Descreva a personalidade desejada",
        example: "Consultiva, profissional, focada em entender as necessidades do cliente",
        required: true,
      },
      {
        id: "agent_emojis",
        type: "input",
        question: "Seu Agente SDR pode usar emojis?",
        placeholder: "Descreva como seu agente deve usar emojis",
        example: "Sim, de forma moderada e profissional em saudações e momentos positivos",
        required: true,
      },
      {
        id: "agent_approach",
        type: "textarea",
        question: "Qual a abordagem inicial do seu Agente SDR?",
        placeholder: "Descreva a abordagem inicial",
        example: "Começar com uma pergunta sobre o desafio atual da empresa do lead",
        required: true,
      },
      {
        id: "qualification_message",
        type: "textarea",
        question: "Qual será a mensagem de qualificação inicial?",
        placeholder: "Digite a mensagem de qualificação",
        example:
          "Para que eu possa direcionar você para a melhor solução, poderia me contar um pouco sobre sua empresa?",
        required: true,
      },
    ],
  },
  {
    title: "QUALIFICAÇÃO E OBJETIVOS",
    description: "Configure as estratégias de qualificação e objetivos do seu Agente SDR",
    steps: [
      {
        id: "qualification_questions",
        type: "textarea",
        question: "Quais perguntas de qualificação (BANT) seu Agente deve fazer?",
        placeholder: "Liste as perguntas de qualificação",
        example:
          "Budget: 'Qual o orçamento previsto para este projeto?'\nAuthority: 'Você é responsável pela decisão de compra?'\nNeed: 'Quais são os principais desafios que você busca resolver?'\nTimeline: 'Quando você planeja implementar esta solução?'",
        required: true,
      },
      {
        id: "qualified_lead_criteria",
        type: "textarea",
        question: "Quais são os critérios mínimos para um lead qualificado?",
        placeholder: "Descreva os critérios mínimos",
        example: "Empresa com mais de 50 funcionários, orçamento mínimo de R$5000/mês, decisor ou influenciador",
        required: true,
      },
      {
        id: "meeting_scheduling_criteria",
        type: "textarea",
        question: "Quando seu Agente deve tentar agendar uma reunião?",
        placeholder: "Descreva os critérios para agendamento",
        example: "Após confirmar pelo menos 3 critérios de qualificação positivos",
        required: true,
      },
      {
        id: "available_meeting_times",
        type: "textarea",
        question: "Quais horários estão disponíveis para agendamento?",
        placeholder: "Liste os horários disponíveis",
        example: "Segunda a sexta, das 9h às 17h, com duração de 30 minutos",
        required: true,
      },
      {
        id: "objection_handling",
        type: "textarea",
        question: "Como seu Agente deve lidar com objeções iniciais?",
        placeholder: "Descreva a estratégia para lidar com objeções",
        example: "Usar técnica SPIN Selling para explorar mais a fundo as necessidades",
        required: true,
      },
    ],
  },
  {
    title: "CONFIGURAÇÕES DE COMUNICAÇÃO",
    description: "Defina as diretrizes de comunicação para o seu Agente SDR",
    steps: [
      {
        id: "communication_language",
        type: "input",
        question: "Em qual idioma seu Agente SDR deve se comunicar?",
        placeholder: "Especifique o idioma e o estilo",
        example: "Português formal mas amigável, sem gírias",
        required: true,
      },
      {
        id: "prospecting_region",
        type: "input",
        question: "Em qual região seu Agente vai prospectar?",
        placeholder: "Especifique a região de foco",
        example: "Brasil - Foco em São Paulo, Rio de Janeiro e Minas Gerais",
        required: true,
      },
      {
        id: "response_style",
        type: "textarea",
        question: "Como devem ser as respostas do seu Agente?",
        placeholder: "Descreva o estilo das respostas",
        example: "Diretas e objetivas, sempre com uma pergunta de continuidade",
        required: true,
      },
      {
        id: "shareable_materials",
        type: "textarea",
        question: "Quais materiais seu Agente pode compartilhar?",
        placeholder: "Liste os materiais disponíveis",
        example: "Cases de sucesso em PDF, apresentação institucional, catálogo de produtos",
        required: true,
      },
      {
        id: "message_tone",
        type: "input",
        question: "Qual o tom das mensagens?",
        placeholder: "Descreva o tom desejado",
        example: "Consultivo e profissional, focado em gerar valor",
        required: true,
      },
      {
        id: "conversation_proactivity",
        type: "input",
        question: "Qual o nível de proatividade nas conversas?",
        placeholder: "Indique o nível de proatividade (1-10)",
        example: "8/10 - Deve ser proativo em qualificar e buscar o agendamento",
        required: true,
      },
    ],
  },
  {
    title: "REGRAS E LIMITAÇÕES",
    description: "Estabeleça as regras e limitações para o seu Agente SDR",
    steps: [
      {
        id: "topics_to_avoid",
        type: "textarea",
        question: "Quais assuntos seu Agente SDR deve evitar?",
        placeholder: "Liste os assuntos a serem evitados",
        example: "Detalhes técnicos muito específicos, preços finais, customizações especiais",
        required: true,
      },
      {
        id: "lead_disqualification_flags",
        type: "textarea",
        question: "Quais são as red flags que desqualificam um lead?",
        placeholder: "Liste as red flags",
        example: "Orçamento muito baixo, empresa muito pequena, setor não atendido",
        required: true,
      },
      {
        id: "human_transfer_criteria",
        type: "textarea",
        question: "Quando transferir para um humano?",
        placeholder: "Descreva as situações para transferência",
        example: "Solicitações muito específicas, grandes contas, negociações complexas",
        required: true,
      },
      {
        id: "confidential_information",
        type: "textarea",
        question: "Quais informações são confidenciais?",
        placeholder: "Liste as informações confidenciais",
        example: "Lista de preços detalhada, nomes de outros clientes, descontos máximos",
        required: true,
      },
      {
        id: "negotiation_limits",
        type: "textarea",
        question: "Quais são os limites de negociação do Agente?",
        placeholder: "Descreva os limites de negociação",
        example: "Pode oferecer apenas demonstração gratuita padrão",
        required: true,
      },
    ],
  },
  {
    title: "CONHECIMENTOS ESPECÍFICOS",
    description: "Forneça informações específicas sobre seu negócio e clientes",
    steps: [
      {
        id: "client_pain_points",
        type: "textarea",
        question: "Quais são as principais dores do seu cliente ideal?",
        placeholder: "Liste as principais dores dos clientes",
        example: "Processos manuais, falta de integração entre sistemas, perda de dados",
        required: true,
      },
      {
        id: "company_differentials",
        type: "textarea",
        question: "Quais são os diferenciais da sua empresa?",
        placeholder: "Liste os principais diferenciais",
        example: "10 anos de mercado, suporte 24/7, implementação em 30 dias",
        required: true,
      },
      {
        id: "success_cases",
        type: "textarea",
        question: "Quais casos de sucesso o Agente pode citar?",
        placeholder: "Descreva casos de sucesso relevantes",
        example: "Ajudamos a empresa X a reduzir custos em 30% em 6 meses",
        required: true,
      },
      {
        id: "priority_products",
        type: "textarea",
        question: "Quais são os produtos/serviços prioritários?",
        placeholder: "Liste os produtos/serviços prioritários",
        example: "Sistema ERP completo, módulo financeiro, consultoria de implantação",
        required: true,
      },
    ],
  },
  {
    title: "REGRAS DE QUALIFICAÇÃO",
    description: "Defina o processo e as regras de qualificação de leads",
    steps: [
      {
        id: "qualification_process",
        type: "textarea",
        question: "Qual é o processo de qualificação (passo a passo)?",
        placeholder: "Descreva o processo de qualificação",
        example:
          "1. Confirmar tamanho da empresa\n2. Identificar principais dores\n3. Verificar orçamento\n4. Confirmar poder de decisão\n5. Agendar demonstração",
        required: true,
      },
      {
        id: "required_information",
        type: "textarea",
        question: "Quais informações são obrigatórias coletar?",
        placeholder: "Liste as informações obrigatórias",
        example: "Nome completo, cargo, e-mail corporativo, telefone, tamanho da empresa",
        required: true,
      },
      {
        id: "unqualified_lead_handling",
        type: "textarea",
        question: "Como lidar com leads não qualificados?",
        placeholderquestion: "Como lidar com leads não qualificados?",
        placeholder: "Descreva o procedimento para leads não qualificados",
        example: "Agradecer o interesse e direcionar para materiais gratuitos/blog",
        required: true,
      },
      {
        id: "initial_offers",
        type: "textarea",
        question: "Quais são as ofertas iniciais permitidas?",
        placeholder: "Liste as ofertas iniciais permitidas",
        example: "Demonstração gratuita de 30 minutos, e-book sobre o setor",
        required: true,
      },
      {
        id: "lead_prioritization",
        type: "textarea",
        question: "Como priorizar os leads?",
        placeholder: "Descreva os critérios de priorização",
        example: "Prioridade para empresas maiores e com necessidade imediata",
        required: true,
      },
    ],
  },
  {
    title: "MÉTRICAS E RESULTADOS",
    description: "Estabeleça as métricas e metas para o seu Agente SDR",
    steps: [
      {
        id: "metrics_to_track",
        type: "textarea",
        question: "Quais métricas o Agente deve registrar?",
        placeholder: "Liste as métricas a serem registradas",
        example: "Número de conversas iniciadas, taxa de qualificação, agendamentos realizados",
        required: true,
      },
      {
        id: "agent_goals",
        type: "textarea",
        question: "Quais são as metas do Agente SDR?",
        placeholder: "Defina as metas do Agente",
        example: "30 leads qualificados por semana, 15 reuniões agendadas",
        required: true,
      },
      {
        id: "qualification_quality_assessment",
        type: "textarea",
        question: "Como avaliar a qualidade das qualificações?",
        placeholder: "Descreva os critérios de avaliação",
        example: "Taxa de comparecimento nas reuniões, taxa de conversão pós-reunião",
        required: true,
      },
    ],
  },
]

